version: "3"

tasks:
  default:
    cmds:
      - task: clean
      - task: package

  prepare:
    sources:
      - index.js
      - info.json
      - remnant2.jpg
      - LICENSE.txt
    generates:
      - dist/index.js
      - dist/info.json
      - dist/remnant2.jpg
      - dist/LICENSE.txt
    cmds:
      - mkdir -p ./dist
      - cp index.js ./dist/
      - cp info.json ./dist/
      - cp remnant2.jpg ./dist/
      - cp LICENSE.txt ./dist/

  package:
    deps:
      - prepare
    vars:
      VERSION:
        sh: node -pe 'p = require("./package.json"); `${p["version"]}`'
    sources:
      - dist/index.js
      - dist/info.json
      - dist/remnant2.jpg
      - dist/LICENSE.txt
    generates:
      - dist/RemnantII_Vortex_Support-v{{.VERSION}}.7z
    cmds:
      - 7z a ./RemnantII_Vortex_Support-v{{.VERSION}}.7z ./dist/*

  package-dev:
    deps:
      - prepare
    vars:
      DESCRIBE:
        sh: git describe --tags --dirty --always
      TIMESTAMP:
        sh: date +%Y%m%d-%H%M
    sources:
      - dist/index.js
      - dist/info.json
      - dist/remnant2.jpg
      - dist/LICENSE.txt
    generates:
      - dist/RemnantII_Vortex_Support-dev-{{.DESCRIBE}}-v{{.TIMESTAMP}}.7z
    cmds:
      - 7z a ./RemnantII_Vortex_Support-dev-{{.DESCRIBE}}-v{{.TIMESTAMP}}.7z ./dist/*

  clean:
    cmds:
      - rm -rf ./dist
      - rm -f ./RemnantII_Vortex_Support-*.7z
