version: "3"

tasks:
  default:
    cmds:
      - task: clean
      - task: package

  prepare:
    sources:
      - assets/
      - src/
      - LICENSE.txt
    generates:
      - dist/index.js
      - dist/info.json
      - dist/gameart.jpg
      - dist/LICENSE.txt
    cmds:
      - pnpm run build

  package:
    deps:
      - prepare
    vars:
      VERSION:
        sh: node -pe 'p = require("./package.json"); `${p["version"]}`'
    sources:
      - dist/index.js
      - dist/info.json
      - dist/remnant2.jpg
      - dist/remnant-save-guardian.png
      - dist/LICENSE.txt
    generates:
      - dist/RemnantII_Vortex_Support-v{{.VERSION}}.7z
    cmds:
      - 7z a -t7z ./RemnantII_Vortex_Support-v{{.VERSION}}.7z ./dist/*

  package-dev:
    deps:
      - prepare
    vars:
      DESCRIBE:
        sh: git describe --tags --dirty --always
      TIMESTAMP:
        sh: date +%Y%m%d-%H%M
    sources:
      - dist/index.js
      - dist/info.json
      - dist/remnant2.jpg
      - dist/remnant-save-guardian.png
      - dist/LICENSE.txt
    generates:
      - dist/RemnantII_Vortex_Support-dev-{{.DESCRIBE}}-v{{.TIMESTAMP}}.7z
    cmds:
      - 7z a ./RemnantII_Vortex_Support-dev-{{.DESCRIBE}}-v{{.TIMESTAMP}}.7z ./dist/*

  clean:
    cmds:
      - rm -rf ./dist
      - rm -f ./RemnantII_Vortex_Support-*.7z
